### ISSUE TITLE
Deployment not working without GUI on server

### ISSUE THREAD

**Issue by Vincent-Nikkelen-mkb** [allmannyttan/matcha-kontraktet-deployment#3]
When installing on a system (Debian 10, VM in Azure) without X11 (which is a common situation) installation fails with the following error:
**Error saving credentials: error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`**

Docker has in their issue list the following:
https://github.com/docker/cli/issues/2229 `"docker login" doesn't run in Linux without X11`

This is blocking our installation as we are not running a GUI. Expectation is that this can be fixed by #2 but in case this ticket is rejected or I am wrong I open this ticket.

**Comment by osirisguitar** [comment]
We should go with #2 and make the packages public.
